In [9]:
import numpy as np
import torch

In [10]:
ords = [
    [1,2,0,3],
    [0,1,4],
    [2,3],
    [3,4],
]

# 5 cates
item_sim = torch.tensor([
    [1,2,3,3,1],
    [2,2,1,1,2],
    [3,1,2,1,3],
    [3,1,1,1,1],
    [1,2,3,1,2]
])

In [11]:
def eval(orders, i_i_sim):
    i_sim = i_i_sim
    print('similarity matrix', i_sim)
    y_truth = [i[-1] for i in orders]
    print('y_truth', y_truth)
    x = [i[0:-1] for i in orders]
    print('x', x)
    y_pred = [torch.sum(i_sim[i], dim=0) for i in x]
    print('y_pred')
    return y_pred

In [12]:
eval(orders=ords, i_i_sim=item_sim)

similarity matrix tensor([[1, 2, 3, 3, 1],
        [2, 2, 1, 1, 2],
        [3, 1, 2, 1, 3],
        [3, 1, 1, 1, 1],
        [1, 2, 3, 1, 2]])
y_truth [3, 4, 3, 4]
x [[1, 2, 0], [0, 1], [2], [3]]
y_pred


[tensor([6, 5, 6, 5, 6]),
 tensor([3, 4, 4, 4, 3]),
 tensor([3, 1, 2, 1, 3]),
 tensor([3, 1, 1, 1, 1])]