In [9]:
import numpy as np
import torch

In [10]:
ords = [
    [1,2,0,3],
    [0,1,4],
    [2,3],
    [3,4],
]

# 5 cates
item_sim = torch.tensor([
    [1,2,3,3,1],
    [2,2,1,1,2],
    [3,1,2,1,3],
    [3,1,1,1,1],
    [1,2,3,1,2]
])

In [11]:
def eval(orders, i_i_sim):
    i_sim = i_i_sim
    print('similarity matrix', i_sim)
    y_truth = [i[-1] for i in orders]
    print('y_truth', y_truth)
    x = [i[0:-1] for i in orders]
    print('x', x)
    y_pred = [torch.sum(i_sim[i], dim=0) for i in x]
    print('y_pred')
    return y_pred

In [12]:
eval(orders=ords, i_i_sim=item_sim)

similarity matrix tensor([[1, 2, 3, 3, 1],
        [2, 2, 1, 1, 2],
        [3, 1, 2, 1, 3],
        [3, 1, 1, 1, 1],
        [1, 2, 3, 1, 2]])
y_truth [3, 4, 3, 4]
x [[1, 2, 0], [0, 1], [2], [3]]
y_pred


[tensor([6, 5, 6, 5, 6]),
 tensor([3, 4, 4, 4, 3]),
 tensor([3, 1, 2, 1, 3]),
 tensor([3, 1, 1, 1, 1])]

In [2]:
from utils.metrics import top_k_accuracy
import numpy as np
import torch

In [7]:
a = torch.tensor([[1,2,3,4],
     [2,3,4,5],
     [5,6,7,8]])

b = [3,2,3]

top_k_accuracy(np.array(a), np.array(b), 1)

0.6666666666666666

In [8]:
import pandas as pd

In [9]:
t = pd.read_csv('data/instacart/interaction.csv', sep='\t')
t

user_id  aisle_id
0             0       111
1             0        87
2             0        22
3             0        37
4             0        36
...         ...       ...
971387    29927        37
971388    29927        71
971389    29927        19
971390    29927        95
971391    29927       110

[971392 rows x 2 columns]

In [15]:
num_user = t['user_id'].max() + 1

In [16]:
u = t['user_id'].to_numpy()
i = t['aisle_id'].to_numpy() + num_user

In [17]:
torch.tensor([u, i])

tensor([[    0,     0,     0,  ..., 29927, 29927, 29927],
        [30039, 30015, 29950,  ..., 29947, 30023, 30038]])