**Reshape image**

In [15]:
import numpy as np

In [17]:
v_feat = np.load('data/instacart/img_feat.npy')

In [18]:
v_feat[0].shape

(768,)

In [14]:
np.save('data/instacart/img_feat.npy', v_feat)

**Check Dim**

In [3]:
import numpy as np

In [4]:
v = np.load('data/instacart/img_feat.npy')
t = np.load('data/instacart/text_feat.npy')

print(v[0].shape, t[0].shape)

(768,) (384,)


In [1]:
from scipy.sparse import csr_matrix
import numpy as np
import pandas as pd

In [2]:
X = np.load('data/instacart/test_dict.npy', allow_pickle=True).item()

In [3]:
X['adj_mat'].shape

torch.Size([127951, 134])

In [6]:
pos = np.nonzero(X['adj_mat'])
print(pos)

tensor([[     0,     12],
        [     0,     19],
        [     0,     22],
        ...,
        [127950,     55],
        [127950,     65],
        [127950,    119]])


: 

**Test score**

In [30]:
def plus(a, b):
    return a+b

In [31]:
scores = {
    f'test@{i}': plus(i, 1) for i in range(0,2)
}

In [32]:
scores

{'test@0': 1, 'test@1': 2}

In [35]:
import numpy as np

# Create a sample matrix
matrix = np.zeros((3, 3))

# Define a list of positions to assign values
positions = [(0, 1), (1, 2), (2, 0)]

# Assign a value to the positions
value = 5
matrix[positions] = value

print(matrix)


[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [7]:
import numpy as np
import torch
from scipy.sparse import csr_matrix

In [5]:
gg = torch.tensor([[1,0,0,1],[0,1,0,0], [1,0,0,0], [0,0,0,1]])
pos = gg.nonzero()
pos

tensor([[0, 0],
        [0, 3],
        [1, 1],
        [2, 0],
        [3, 3]])

In [11]:
spr_mat = csr_matrix(gg)
print(spr_mat)

  (0, 0)	1
  (0, 3)	1
  (1, 1)	1
  (2, 0)	1
  (3, 3)	1
